name: thesis_portfolio
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.10.0=py312hca03da5_0
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py312hca03da5_0
  - argon2-cffi=25.1.0=py312hca03da5_0
  - argon2-cffi-bindings=25.1.0=py312h254cc4a_0
  - asttokens=3.0.0=py312hca03da5_0
  - async-lru=2.0.5=py312hca03da5_0
  - attrs=25.4.0=py312hca03da5_2
  - babel=2.17.0=py312hca03da5_0
  - beautifulsoup4=4.14.2=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=6.3.0=py312hca03da5_0
  - bottleneck=1.4.2=py312h03d0aa3_1
  - brotlicffi=1.2.0.0=py312h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.01.04=py312hca03da5_0
  - cffi=2.0.0=py312h73c2a22_1
  - charset-normalizer=3.4.4=py312hca03da5_0
  - comm=0.2.3=py312hca03da5_0
  - contourpy=1.3.3=py312h20e30b6_0
  - cycler=0.12.1=py312hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py312h50f4ffc_1
  - decorator=5.2.1=py312hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py312hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py312haa24f5a_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py312hca03da5_1
  - harfbuzz=12.3.0=h9837a22_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py312hca03da5_0
  - httpx=0.28.1=py312hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py312hca03da5_0
  - ipykernel=6.31.0=py312h7eb115d_0
  - ipython=9.7.0=py312hca03da5_0
  - ipython_pygments_lexers=1.1.1=py312hca03da5_0
  - ipywidgets=8.1.7=py312hca03da5_0
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - joblib=1.5.3=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=py312hca03da5_0
  - jsonschema=4.25.1=py312hca03da5_0
  - jsonschema-specifications=2025.9.1=py312hca03da5_0
  - jupyter=1.1.1=py312hca03da5_0
  - jupyter-lsp=2.2.5=py312hca03da5_0
  - jupyter_client=8.8.0=py312hca03da5_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.9.1=py312hca03da5_0
  - jupyter_events=0.12.0=py312hca03da5_1
  - jupyter_server=2.17.0=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=py312hca03da5_0
  - jupyterlab=4.5.0=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=py312hca03da5_0
  - jupyterlab_server=2.28.0=py312hca03da5_0
  - jupyterlab_widgets=3.0.16=py312hca03da5_0
  - kiwisolver=1.4.9=py312haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - libsodium=1.0.20=h897f8a9_0
  - libtiff=4.7.1=h367c460_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.8=py312hca03da5_0
  - matplotlib-base=3.10.8=py312haa222d5_0
  - matplotlib-inline=0.2.1=py312hca03da5_0
  - mistune=3.1.2=py312hca03da5_0
  - nbclient=0.10.2=py312hca03da5_0
  - nbconvert=7.16.6=py312hca03da5_0
  - nbconvert-core=7.16.6=py312hca03da5_0
  - nbconvert-pandoc=7.16.6=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - notebook=7.5.0=py312hca03da5_0
  - notebook-shim=0.2.4=py312hca03da5_0
  - numexpr=2.14.1=py312h5fbe615_0
  - numpy=2.4.1=py312h4bb6f22_0
  - numpy-base=2.4.1=py312h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py312hca03da5_1
  - pandas=2.3.3=py312h3f644e9_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py312hca03da5_0
  - parso=0.8.5=py312hca03da5_0
  - patsy=1.0.2=py312hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py312hca03da5_1
  - pillow=12.1.0=py312h7b5562e_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py312hca03da5_0
  - prometheus_client=0.21.1=py312hca03da5_0
  - prompt-toolkit=3.0.52=py312hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312haa24f5a_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py312hca03da5_0
  - pycparser=2.23=py312hca03da5_0
  - pygments=2.19.2=py312hca03da5_0
  - pyparsing=3.2.5=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.12=h2bfc596_1
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.21.2=py312hca03da5_0
  - python-json-logger=4.0.0=py312hca03da5_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py312hca03da5_0
  - pyyaml=6.0.3=py312h091b9d3_0
  - pyzmq=27.1.0=py312h5a8c52c_1
  - qtconsole=5.7.0=py312hca03da5_0
  - qtpy=2.4.3=py312hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py312hca03da5_0
  - requests=2.32.5=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.28.0=py312h931abed_0
  - scikit-learn=1.8.0=py312h003a250_0
  - scipy=1.16.3=py312h08a1045_0
  - seaborn=0.13.2=py312hca03da5_3
  - send2trash=1.8.3=py312hca03da5_0
  - setuptools=80.10.1=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sniffio=1.3.1=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py312hca03da5_0
  - statsmodels=0.14.6=py312haa24f5a_0
  - terminado=0.18.1=py312hca03da5_0
  - threadpoolctl=3.5.0=py312h7eb115d_1
  - tinycss2=1.4.0=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py312haa24f5a_0
  - traitlets=5.14.3=py312hca03da5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py312hca03da5_0
  - wcwidth=0.2.14=py312hca03da5_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.46.3=py312hca03da5_0
  - widgetsnbextension=4.0.14=py312hca03da5_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/anaconda3/envs/thesis_portfolio
